name: Run test
on: push

jobs:
  run-test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install go-jsonnet
        run: |
          # https://github.com/argoproj/argo-cd/blob/v2.6.8/go.mod#L40
          go install github.com/google/go-jsonnet/cmd/jsonnet@v0.19.1

      - name: Run test
        run: |
          jsonnet machete/test/*.jsonnet
